# Autogenerated by devscripts/update-version.py

__version__ = '2023.08.12.0001'

RELEASE_GIT_HEAD = '164d9c6b253ef79dec34f8999c0559eccb19bb49'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
