# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.06.024938'

RELEASE_GIT_HEAD = '6adf62a5099192b42558aeebc17341eae05eb0cd'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'observeroftime01/yt-dlp'

ORIGIN = 'observeroftime01/yt-dlp'

_pkg_version = '2024.03.06.024938'
