# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.08.031124'

RELEASE_GIT_HEAD = 'd895e9423dc8709c66403f5c778234ee40accf2c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'observeroftime01/yt-dlp'

ORIGIN = 'observeroftime01/yt-dlp'

_pkg_version = '2024.01.08.031124'
